# Generated by Django 4.2.16 on 2024-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                ("updated_at", models.DateTimeField(verbose_name="date updated")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                ("updated_at", models.DateTimeField(verbose_name="date updated")),
                ("summary", models.CharField(max_length=10)),
                ("progress", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                ("updated_at", models.DateTimeField(verbose_name="date updated")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "Todo"),
                            ("IN_PROGRESS", "Inprogress"),
                            ("DONE", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=10)),
                ("progress", models.IntegerField(default=0)),
            ],
        ),
    ]
