# Generated by Django 4.2.16 on 2024-10-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.asignee",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="proejct",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.project",
            ),
            preserve_default=False,
        ),
    ]
