# Generated by Django 4.2.16 on 2024-10-25 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_asignee_manager_task_proejct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="proejct",
            new_name="project",
        ),
    ]
