# Generated by Django 4.2.16 on 2024-10-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_proejct_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pr_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
