# Generated by Django 4.2.16 on 2024-10-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_task_asignee_alter_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
    ]
