# Generated by Django 4.2.16 on 2024-10-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_project_name_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="weightage",
            field=models.IntegerField(default=0),
        ),
    ]
