# Generated by Django 4.2.16 on 2024-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_task_weightage"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
