# Generated by Django 4.2.16 on 2024-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_task_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                ("updated_at", models.DateTimeField(verbose_name="date updated")),
                (
                    "last_synced_at",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="last synced at",
                    ),
                ),
            ],
        )
    ]
