# Generated by Django 4.2.16 on 2024-10-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_board_project_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.board",
            ),
            preserve_default=False,
        ),
    ]
