# Generated by Django 4.2.16 on 2024-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_project_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="summary",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
